plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: minima
remote_theme: jekyll/minima
markdown: kramdown
github:
  is_project_page: false
title: Learning Malagasy and Tsimihety with Bako
description: A resource for language learners in Mandritsara, Madagascar
  header_pages:
  - introduction/index.md
  - grammar/index.md
extra:
  analytics:
    provider: google
    property: G-DG828TL4V1
extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
